apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth-service
  template:
    metadata:
      labels:
        app: auth-service
    spec:
      containers:
        - name: auth-service
          image: andresd2314/auth-service:1.0
          ports:
            - containerPort: 11234
          env:
            - name: SPRING_DATASOURCE_URL
              value: jdbc:mysql://security-db:3306/users
            - name: SPRING_DATASOURCE_USERNAME
              value: root
            - name: SPRING_DATASOURCE_PASSWORD
              value: root
