apiVersion: apps/v1
kind: Deployment
metadata:
  name: security-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: security-db
  template:
    metadata:
      labels:
        app: security-db
    spec:
      containers:
        - name: mysql
          image: mysql:5.7
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: root
            - name: MYSQL_DATABASE
              value: users
          ports:
            - containerPort: 3306
          volumeMounts:
            - name: mysql-storage
              mountPath: /var/lib/mysql
      volumes:
        - name: mysql-storage
          persistentVolumeClaim:
            claimName: mysql-pvc
